# Generated by Django 3.2 on 2023-06-18 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='อายุ')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ความสนใจของลูกค้า')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ที่มาของลูกค้า')),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='เว็บไซต์ทำการตลาด')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='เบอร์โทรศัพท์')),
                ('user_id_customer', models.CharField(blank=True, max_length=255, verbose_name='User login')),
                ('user_password_customer', models.CharField(blank=True, max_length=255, verbose_name='Password')),
                ('user_bank_name', models.CharField(blank=True, max_length=255, verbose_name='ชื่อบัญชี')),
                ('user_id_bank', models.CharField(blank=True, max_length=255, verbose_name='หมายเลขบัญชีธนาคาร')),
                ('buy', models.CharField(blank=True, choices=[('ซื้อ', 'ซื้อ'), ('ยังไม่ซื้อ', 'ยังไม่ซื้อ')], default='ยังไม่ซื้อ', max_length=50, verbose_name='สถานะซื้อ')),
                ('sex', models.CharField(blank=True, choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=10, verbose_name='เพศ')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='จำนวนซื้อ')),
                ('unit', models.CharField(blank=True, choices=[('บาท', 'บาท')], default='บาท', max_length=10, null=True, verbose_name='หน่วย')),
                ('call_back', models.CharField(blank=True, choices=[('Line', 'Line'), ('Facebook', 'Facebook'), ('Tiktok', 'Tiktok'), ('Youtube', 'Youtube'), ('Website', 'Website'), ('Other', 'Other')], max_length=100, null=True, verbose_name='ติดต่อลูกค้า')),
                ('other', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.CharField(blank=True, max_length=255, verbose_name='ช่องทางติดต่อ FB')),
                ('line', models.CharField(blank=True, max_length=255, verbose_name='ช่องทางติดต่อ Line')),
                ('check', models.BooleanField(default='')),
                ('check_user', models.CharField(blank=True, choices=[('รออนุมัติ', 'รออนุมัติ'), ('อนุมัติ', 'อนุมัติ')], default='รออนุมัติ', max_length=10, null=True, verbose_name='หน่วย')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sale.age')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sale.interest')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sale.source')),
                ('user_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('web', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sale.web')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'Sale',
                'ordering': ['-id'],
            },
        ),
    ]
