# Generated by Django 3.2 on 2023-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='check_user',
            field=models.BooleanField(default=True),
        ),
    ]
