# Generated by Django 3.2.3 on 2023-06-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0002_auto_20230618_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='check_user',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
