# Generated by Django 3.2.3 on 2023-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0004_alter_sale_check_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='check_user',
            field=models.BooleanField(blank=True, default=True, verbose_name='อนุมัติ'),
        ),
    ]
