# Generated by Django 3.2.3 on 2023-06-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sale', '0005_alter_sale_check_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ธนาคาร'),
        ),
    ]
