# Generated by Django 3.2 on 2023-06-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0039_alter_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_status',
            field=models.CharField(blank=True, choices=[('ใช้งานได้', 'ใช้งานได้'), ('ชำรุด', 'ชำรุด')], max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('สต๊อก', 'สต๊อก'), ('ยืม', 'ยืม')], max_length=100),
        ),
    ]
