# Generated by Django 3.2.3 on 2023-06-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0041_auto_20230605_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='detail',
            field=models.TextField(max_length=255, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
