# Generated by Django 3.2.3 on 2023-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0042_alter_stock_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_status',
            field=models.CharField(blank=True, choices=[('ใช้งานได้', 'ใช้งานได้'), ('ชำรุด', 'ชำรุด')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_status',
            field=models.CharField(blank=True, choices=[('สต๊อก', 'สต๊อก'), ('ยืม', 'ยืม')], default='', max_length=100),
        ),
    ]
