# Generated by Django 3.2.3 on 2023-06-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0043_auto_20230615_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image_profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='image_item', verbose_name='ภาพสินค้า'),
        ),
    ]
