# Generated by Django 3.2.3 on 2023-06-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0044_stock_image_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='image_profile',
            new_name='image_item',
        ),
    ]
