# Generated by Django 3.2.3 on 2023-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0045_rename_image_profile_stock_image_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image_item',
            field=models.ImageField(blank=True, default='notebook-default.jpg', null=True, upload_to='image_item', verbose_name='ภาพสินค้า'),
        ),
    ]
