# Generated by Django 3.2.3 on 2023-06-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_stock', '0046_alter_stock_image_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item_model',
            field=models.CharField(max_length=60, null=True, verbose_name='รุ่นสินค้า'),
        ),
    ]
