# Generated by Django 3.2.3 on 2023-06-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_money', '0010_auto_20230529_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorary',
            options={'ordering': ['-id'], 'verbose_name': 'Money', 'verbose_name_plural': 'Sorary'},
        ),
    ]
