# Generated by Django 3.2.3 on 2023-06-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kpi', '0018_rename_user_interrest_create_interrest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='team',
        ),
    ]
