# Generated by Django 3.2.3 on 2023-06-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0056_alter_profileuser_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['username'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
    ]
