# Generated by Django 3.2.3 on 2023-06-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0058_alter_profileuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ธนาคาร'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='bank_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='ชื่อบัญชี'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, verbose_name='ชื่อเล่น'),
        ),
    ]
