# Generated by Django 3.2 on 2023-06-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0059_auto_20230619_1733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['-worked_date'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
    ]
