# Generated by Django 3.2 on 2023-06-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0060_alter_profileuser_options'),
        ('app_user', '0060_auto_20230624_0856'),
    ]

    operations = [
    ]
