# Generated by Django 3.2 on 2023-06-25 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0061_merge_20230624_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={'ordering': ['-username'], 'verbose_name': 'Member', 'verbose_name_plural': 'Profile'},
        ),
    ]
